specVersion: 0.2.0
name: subqlHelloWorld
node: version ^0.33.0
version: 0.0.4
description: >-
  This project can be use as a starting point for developing your SubQuery
  project
repository: 'https://github.com/subquery/subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - kind: substrate/Runtime
    startBlock: 5000000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: system
            method: NewAccount
        - handler: handleAccountsByBlock
          kind: substrate/EventHandler
          filter:
            module: system
            method: NewAccount
        - handler: handleAccountsByDate
          kind: substrate/EventHandler
          filter:
            module: system
            method: NewAccount